### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by oliviermaridat** [jmechnich/qtposition_gpsd#1]
Hi jmechnich,

Thank you for your work on gpsd! Its great to have that with QtPositionning.
What is the license of your qtposition_gpsd? Would you be willing to provide it as MIT or LGPL3+ like Qt?

**Comment by jmechnich** [comment]
Hi Olivier,

most certainly. Let me get back to you once I have decided which license to use.

Cheers,
Jörg

**Comment by jmechnich** [comment]
Hi again,

the project shall be put under a MIT license and all relevant information should be available in the repo now. Please let me know if you require anything else. In any case, I'd be happy to learn what project you are using the code with.

Cheers,
Jörg

**Comment by oliviermaridat** [comment]
Thank you @jmechnich ! I intended to use it as an easy way to access GPS data on a Linux put into an electric vehicle (GPS data was not the goal of the project, just a bonus), but project has been postponed. Anyway, "qtposition_gpsd" is definitely in my "to be used" list ;-)
